[env]
TERM = "xterm-256color"

[font]
size = 18.0
normal = { family = "Lekton Nerd Font Mono", style = "Regular" }
bold = { family = "Lekton Nerd Font Mono", style = "Bold" }
italic = { family = "Lekton Nerd Font Mono", style = "Regular" }

[colors]
[colors.cursor]
text = "#181818"
cursor = "#ffffff"

[window]
padding = { x = 3, y = 3 }
decorations = "Buttonless"

[scrolling]
history = 20000
multiplier = 3
