[env]
TERM = "xterm-256color"

[font]
size = 14.0
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
# italic = { family = "GoMono Nerd Font Mono", style = "Italic" }

[colors]
[colors.cursor]
text = "#181818"
cursor = "#ffffff"

[window]
padding = { x = 3, y = 3 }
decorations = "Buttonless"

[scrolling]
history = 1000
multiplier = 3
